tickers:
  # Metals
  - GC=F        # Gold
  - SI=F        # Silver
  - HG=F        # Copper
  - PL=F        # Platinum
  - PA=F        # Palladium

  # Energy
  - CL=F        # WTI Crude
  - BZ=F        # Brent Crude
  - NG=F        # Natural Gas
  - RB=F        # Gasoline RBOB
  - HO=F        # Heating Oil

  # Agriculture
  - ZC=F        # Corn
  - ZS=F        # Soybeans
  - ZW=F        # Wheat
  - CT=F        # Cotton No.2
  - KC=F        # Coffee
  - SB=F        # Sugar
  - CC=F        # Cocoa
  - LB=F        # Lumber

  # Interest Rates / Bonds
  - ^IRX        # US 13-Week T-Bill Yield
  - ^FVX        # US 5-Year Yield
  - ^TNX        # US 10-Year Yield
  - ^TYX        # US 30-Year Yield

  # Currencies (Futures)
  - DX-Y.NYB    # US Dollar Index
  - EURUSD=X    # Euro / USD
  - JPY=X       # USD / JPY
  - GBPUSD=X    # British Pound / USD

  # ETFs / Misc
  - URA         # Uranium ETF
  - SPY         # S&P 500 ETF
  - QQQ         # Nasdaq 100 ETF
  - IWM         # Russell 2000 ETF


history_days: 800      # enough to compute SMA200 and give chart context
chart_lookback: 400
output_dir: docs
csv_filename: latest_prices_sma.csv
dashboard_title: "Price & SMA Dashboard"